version: '3.8'

services:
  # 1. Cơ sở dữ liệu PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: nckh_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nckh_user
      POSTGRES_PASSWORD: nckh_password
      POSTGRES_DB: nckh_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nckh-network

  # 2. Redis (Bộ nhớ đệm)
  redis:
    image: redis:alpine
    container_name: nckh_redis
    ports:
      - "6379:6379"
    networks:
      - nckh-network

  # 3. PgAdmin (Giao diện xem Database - Giống Excel)
  pgadmin:
    image: dpage/pgadmin4
    container_name: nckh_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - nckh-network

volumes:
  postgres_data:


networks:
  nckh-network:
